"use client"

import { useState } from "react"
import { zodResolver } from "@hookform/resolvers/zod"
import { useForm, type SubmitHandler } from "react-hook-form"
import { z } from "zod"
import { Bot, Loader2, Sparkles } from "lucide-react"

import { getWorkoutRecommendation, type WorkoutRecommendationOutput } from "@/ai/flows/workout-recommendation"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form"
import { Textarea } from "@/components/ui/textarea"
import { useToast } from "@/hooks/use-toast"

const formSchema = z.object({
  workoutHistory: z.string().min(10, {
    message: "Please provide a brief workout history.",
  }),
  fitnessGoals: z.string().min(10, {
    message: "Please describe your fitness goals.",
  }),
  studentPreferences: z.string().optional(),
})

type FormValues = z.infer<typeof formSchema>

export function RecommendationForm() {
  const [recommendation, setRecommendation] = useState<WorkoutRecommendationOutput | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const { toast } = useToast()

  const form = useForm<FormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      workoutHistory: "",
      fitnessGoals: "",
      studentPreferences: "",
    },
  })

  const onSubmit: SubmitHandler<FormValues> = async (data) => {
    setIsLoading(true)
    setRecommendation(null)
    try {
      const result = await getWorkoutRecommendation(data)
      setRecommendation(result)
    } catch (error) {
      console.error("Failed to get workout recommendation:", error)
      toast({
        title: "Error",
        description: "Failed to generate workout recommendation. Please try again.",
        variant: "destructive",
      })
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="grid md:grid-cols-2 gap-8">
      <Card>
        <CardHeader>
          <CardTitle className="font-headline">AI Workout Generator</CardTitle>
          <CardDescription>
            Fill in the details below to get a personalized workout plan generated by AI.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
              <FormField
                control={form.control}
                name="workoutHistory"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Workout History</FormLabel>
                    <FormControl>
                      <Textarea placeholder="e.g., 3x a week, focusing on cardio..." {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="fitnessGoals"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Fitness Goals</FormLabel>
                    <FormControl>
                      <Textarea placeholder="e.g., Lose 10kg, build muscle, run a 5k..." {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="studentPreferences"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Preferences (Optional)</FormLabel>
                    <FormControl>
                      <Textarea placeholder="e.g., I prefer free weights, dislike running..." {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <Button type="submit" disabled={isLoading}>
                {isLoading ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Sparkles className="mr-2 h-4 w-4" />
                    Generate Plan
                  </>
                )}
              </Button>
            </form>
          </Form>
        </CardContent>
      </Card>
      
      <div className="space-y-4">
        <Card className="min-h-[300px]">
          <CardHeader className="flex flex-row items-center gap-2">
            <Bot className="w-6 h-6 text-primary" />
            <CardTitle className="font-headline">Your New Workout</CardTitle>
          </CardHeader>
          <CardContent>
            {isLoading && (
              <div className="flex flex-col items-center justify-center h-full text-muted-foreground">
                <Loader2 className="w-8 h-8 animate-spin mb-4" />
                <p>Generating your personalized plan...</p>
              </div>
            )}
            {!isLoading && !recommendation && (
              <div className="flex flex-col items-center justify-center h-full text-muted-foreground">
                <p>Your recommended workout will appear here.</p>
              </div>
            )}
            {recommendation && (
              <div className="prose prose-sm dark:prose-invert max-w-none whitespace-pre-wrap">
                {recommendation.workoutRecommendation}
              </div>
            )}
          </CardContent>
        </Card>
        {recommendation?.reasoning && (
           <Card>
            <CardHeader>
                <CardTitle className="font-headline text-base">Reasoning</CardTitle>
            </CardHeader>
             <CardContent>
                <p className="text-sm text-muted-foreground whitespace-pre-wrap">{recommendation.reasoning}</p>
             </CardContent>
           </Card>
        )}
      </div>
    </div>
  )
}
